# traefik "dynamic" config

# development env setup
# so no tls anything
http:
  routers:
    # wetfish.net blogpost frontpage
    fishblog:
      entrypoints:
        - "web"
      rule: "Host(`wetfish.net`)"
      service: "fishblog"
    
    # danger.wetfish.net
    danger:
      entrypoints:
       - "web"
      rule: "Host(`danger.wetfish.net`)"
      service: "danger"

  services:
    fishblog:
      loadBalancer:
        servers:
          # "container_name: fishblog-app" in blog compose stack
          - url: "http://fishblog-app.:2304"
    
    danger:
      loadbalancer:
        servers:
          # "container_name: danger-web" in danger compose stack
          - url: "http://danger-web.:80"
