# traefik "dynamic" config

# development env setup
# so no tls anything
http:
  routers:
    # wetfish.net blogpost frontpage
    fishblog:
      entrypoints:
        - "web"
      rule: "Host(`wetfish.net`)"
      service: "fishblog"
    
    # danger.wetfish.net
    danger:
      entrypoints:
       - "web"
      rule: "Host(`danger.wetfish.net`)"
      service: "danger"

    # wetfishonline.com
    online:
      entrypoints:
        - "web"
      rule: "Host(`wetfishonline.com`)"
      service: "online"
    
    # glitch.wetfish.net
    glitch:
      entrypoints:
        - "web"
      rule: "Host(`glitch.wetfish.net`)"
      service: "glitch"

    # click.wetfish.net
    click:
      entrypoints:
        - "web"
      rule: "Host(`click.wetfish.net`)"
      service: "click"

    # wiki.wetfish.net
    wiki:
      entrypoints:
        - "web"
      rule: "Host(`wiki.wetfish.net`)"
      service: "wiki"

  services:
    fishblog:
      loadBalancer:
        servers:
          # "container_name: fishblog-app" in blog compose stack
          - url: "http://fishblog-app.:2304"
    
    danger:
      loadBalancer:
        servers:
          # "container_name: danger-web" in danger compose stack
          - url: "http://danger-web.:80"

    online:
      loadBalancer:
        servers:
          # "container_name: online-web" in online compose stack
          - url: "http://online-web.:80"

    glitch:
      loadBalancer:
        servers:
          # "container_name: glitch-web" in glitch compose stack
          - url: "http://glitch-web.:80"

    click:
      loadBalancer:
        servers:
          # "container_name: click-web" in click compose stack
          - url: "http://click-web.:80"
    
    wiki:
      loadBalancer:
        servers:
          # "container_name: wiki-web" in wiki compose stack
          - url: "http://wiki-web.:80"
