# traefik "static" config

# development env setup
# so no tls anything
log:
  level: DEBUG
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls: {}
      #   domains:
      #     - main: wetfish.net
      #     - main: danger.wetfish.net
      #     - main: wetfishonline.com
      #     - main: glitch.wetfish.net
      #     - main: click.wetfish.net
      #     - main: wiki.wetfish.net

# dynamic config
providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
    debugLogGeneratedTemplate: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "letsencrypt@wetfish.net"
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: web

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  fields:
    defaultMode: keep
    names:
      ClientUsername: keep
    headers:
      defaultMode: keep
      names:
          User-Agent: keep
          Authorization: drop
          Content-Type: keep
